config/routes.rb
Rails.application.routes.draw do

  # show homepage route
  root 'static_pages#home'
  
  # static pages routes
  get  '/about',   to: 'static_pages#about'
  get  '/learn', to: 'static_pages#learn'
  get  '/time', to: 'chart#time'
  post 'feed', to: 'chart#feed'
  get  '/feed', to: 'chart#feed'
  get  '/twitter/show', to: 'twitter#show'
  post '/twitter/show', to: 'twitter#show'
  get 'hail/show', to: 'hail#show'
  post 'hail/show', to: 'hail#show'

  
  # sign-up routes: show page and process form
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  # log-in routes: show page and process form
  get  'sessions/new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  
  # log-out routes: process the form
  delete '/logout',  to: 'sessions#destroy'
  
  # resourceful routes for Create, Retrieve, Update and Destroy users
  resources :users
  resources :account_activations, only: [:edit]

end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  before_action :is_logged_in
  
  def is_logged_in
    redirect_to("/login") if current_user.blank?
  end
  
  def time
   
  end

  def feed
     @state = params[:state]
     if @state != nil
      @text = "Total number of tornadoes in #{@state} in 2016 is:#{Tornado.where(:st => @state).count}"
     else
      @text = "No State has been selected"
     end
  end

end

app/helpers/chart_helper.rb
module ChartHelper
end

app/views/chart/feed.html.erb
<% provide(:title, "Feed") %>
<body class="feed">
    <h2>Tornadoes - Annual 2016 - part 2</h2>
    <p>[Source: NOAA National Centers for Environmental Information, State of the Climate: Tornadoes for Annual 2016, published online January 2017, 
       retrieved on November 25, 2017 from https://www.ncdc.noaa.gov/sotc/tornadoes/201613].</p>
    <p>With the exception of February, each month had a near- to below-average number of tornadoes. 
       In February, there were 102 confirmed tornadoes, above the 1991-2010 average of 29. 
       In June, there were 86 confirmed tornadoes, much less than the average of 243.
       At a statewide level, the number of tornadoes for the year was at least double the average in Alabama (87 vs 44) and Indiana (40 vs 22), 
       but less than half in North Carolina (16 vs 31), South Dakota (16 vs 36) and Tennessee (10 vs 26).</p>
    <!-- chart 1: barchart tornadoes/state -->
    <h2>USA tornadoes of 2016</h2>
    <p>The following bar chart provides information about the global amount of tornadoes in 2016 in each State</p><br>
    <div class="jumbotron myBackground4">
        <p><b>USA tornadoes 2016</b></p><br>
        <%= bar_chart Tornado.group(:st).count, id: "users-chart", width: "1020px", height: "700px", xtitle: "Total number of tornadoes", ytitle: "State" %>
    </div>
    <!-- chart 2: tornadoes/days per state -->
    <h2>USA tornadoes of 2016 by state</h2>
    <p>Additional information on individual outbreaks is available in our monthly tornado reports.</p><br>
    <div class="jumbotron myBackground4">
        <p><b>Statistics by State</b></p><br>
        <!-- drop down menu code -->
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <p>Type in State abbreviation</p>
                <%= form_tag feed_path do |f| %>
                <%= text_field_tag :state, nil, placeholder: "Select State", class: 'form-control' %>
                <%= submit_tag "Get Statistics", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div><br>
      <p><%= @text %></p>
      <br>
      <p><b>Tornadoes trend in 2016</b></p>
      <%= line_chart Tornado.where(:st => @state).group_by_day(:date).count, xtitle: "Time", ytitle: "Number of tornadoes" %>
      <br>
      <p><b>F-scale trend chart</b></p>
      <%= bar_chart Tornado.where(:st => @state).group(:date).sum(:mag), id: "users-chart-2", width: "1020px", height: "700px", xtitle: "F-scale", ytitle: "Date" %>
      <br>
    </div>
    <br><br><br><br>
</body>

app/views/chart/time.html.erb
<!-- import highchart.js -->
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<% provide(:title, "Feed") %>
<body class="time">
  <h2>Tornadoes - Annual 2016 - part 1</h2>
  <p>[Source: NOAA National Centers for Environmental Information, State of the Climate: Tornadoes for Annual 2016, published online January 2017, 
     retrieved on November 25, 2017 from https://www.ncdc.noaa.gov/sotc/tornadoes/201613].</p>
  <p>Similar to the previous four years, tornado activity across the U.S. during 2016 was below average. 
     During January-August, there were 843 confirmed tornado reports, with 142 reports still pending for September-December. 
     This brings the 2016 preliminary tornado count to 985, with the final count expected to be lower. 
     As with most years, there were several large and destructive tornado and severe weather outbreaks during 2016.</p><br>
  <p>The following charts provide a graphical representation of this trend in 2016.</p><br>
  <!-- chart 1: tornadoes/days -->
  <div class="jumbotron myBackground4">
    <p><b>2016 US tornadoes - daily distribution</b></p><br>
    <%= line_chart Tornado.group_by_day(:date).count, xtitle: "Date", ytitle: "Number of tornadoes" %>
  </div>
  <br>
  <p>There were 17 tornado-related fatalities in 2016, much lower than the long-term average. 
     The deadliest single tornado of the year occurred in Louisiana and Mississippi on February 23rd, when an EF-3 killed six people. 
     Another EF-3 occurred on November 29th in Alabama, resulting in five fatalities. May was an active month with 216 confirmed tornadoes. 
     Of those, there were 2 EF-4's, one reported on May 9th and May 25th. </p>
  <!-- chart 2: tornadoes/months -->
  <div class="jumbotron myBackground4">
    <p><b>2016 US tornadoes - monthly distribution</b></p><br>
    <%= line_chart Tornado.group_by_month(:date).count, xtitle: "Month", ytitle: "Number of Tornadoes" %>
  </div>
  <br>
  <!-- Chart 3: million$loss/time-->
  <p>The deadliest tornado outbreaks of the year occurred in late February and in November, 
  with strong tornadoes striking across the South, killing seven and five people, respectively. 
  In 2016, there were eight severe weather outbreaks that caused damages exceeding one billion U.S. dollars.</p>
  <p>Details of the global costs caused by tornadoes in 2016 are displayed in the chart below.</p>
  <br>
  <div class="jumbotron myBackground4">
    <p><b>2016 US tornadoes - Overall cost of damages</b></p><br>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <%= content_tag "div", id: "items", data: {url: Tornado.order('date ASC') } do %>
    <% end %>
  </div>
  <br>
</body>