config/routes.rb
Rails.application.routes.draw do

  # show homepage route
  root 'static_pages#home'
  
  # static pages routes
  get  '/about',   to: 'static_pages#about'
  get  '/learn', to: 'static_pages#learn'
  get  '/time', to: 'chart#time'
  post 'feed', to: 'chart#feed'
  get  '/feed', to: 'chart#feed'
  get  '/twitter/show', to: 'twitter#show'
  post '/twitter/show', to: 'twitter#show'
  get 'hail/show', to: 'hail#show'
  post 'hail/show', to: 'hail#show'

  
  # sign-up routes: show page and process form
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  # log-in routes: show page and process form
  get  'sessions/new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  
  # log-out routes: process the form
  delete '/logout',  to: 'sessions#destroy'
  
  # resourceful routes for Create, Retrieve, Update and Destroy users
  resources :users
  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><br>
    <div class="col-sm-5">
      <small>
        This app uses open data from the <a href="http://www.spc.noaa.gov/wcm/">National Oceanic and Atmosferic Administration</a> website
      </small>
    </div>
    <div class="col-sm-2">
      <%= link_to image_tag("NOAA_emblem.png", alt: "NOAA logo"), 'http://www.noaa.gov/' %>
    </div>
    <div class="col-sm-5">
      <ul class="social">
        <li><iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fpeaceful-peak-81480.herokuapp.com%2Fcontact&layout=button&size=large&mobile_iframe=true&width=73&height=28&appId" width="73" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></li>
        <li><iframe src="https://platform.twitter.com/widgets/tweet_button.html?size=l&url=https%3A%2F%2Fpeaceful-peak-81480.herokuapp.com%2F" width="140" height="28" title="Twitter Tweet Button" style="border: 0; overflow: hidden;"></iframe></li>
      </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="col-sm-6">
    <%= link_to "the tornados app", root_path, id: "logo" %>
  </div>
  <div class="container">
    <div class="col-6">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Learn", learn_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% if current_user.admin? == true %>
                <li><%= link_to "Users", users_path %></li>
              <% end %>
              <li><%= link_to "Report 2016 - part1", '/time', :"data-turbolinks" => false %></li>
              <li><%= link_to "Report 2016 - part2", '/feed', :"data-turbolinks" => false %></li>
              <li><%= link_to "Report 2016 - part3", '/hail/show', :"data-turbolinks" => false %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
</header>
              

app/views/layouts/_rails_default.html.erb
<!-- A partial file that links to the application layout file for the Rails's default header class -->
    
    
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!-- This is a partial file that informs the Internet Explorer browser that if its version is 
less than 9, then it will need Javascript to run the HTML5 that is featured in the application.-->    
    
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container main">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      
      <div class="matteo">
        <%= yield %>
      </div>
      
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
    <center><%= render 'layouts/footer' %></center>
  </body>
</html>